package com.mohamedheshsam.main.respository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.mohamedheshsam.main.models.Product;

public interface ProductRepository extends JpaRepository<Product, Long> {
  List<Product> findByCategoryName(String category);

  List<Product> findByBrand(String brand);

  List<Product> findByCategoryNameAndBrand(String category, String brand);

  List<Product> findByName(String name);

  // Query cause it wasn't automatically generated by spring data jpa
  @Query("""
        SELECT p FROM Product p
         WHERE LOWER(p.brand) = LOWER(:brand)
           AND LOWER(p.name)  = LOWER(:name)
      """)
  List<Product> findByBrandAndName(@Param("brand") String brand,
      @Param("name") String name);

  Long countByBrandAndName(String brand, String name);
}
