server:
  port: ${SERVER_PORT:8080}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?sslMode=REQUIRED
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        ddl:
          auto: ${HIBERNATE_DDL_AUTO:update}

api:
  prefix: ${API_PREFIX:/api/v1}

auth:
  token:
    expiration: ${TOKEN_EXPIRATION}
    jwtSecret: ${JWT_SECRET}
